apiVersion: v1
kind: Secret
metadata:
  name: autoparts-secrets
  namespace: autoparts
type: Opaque
stringData:
  postgres-password: autoparts_pass
  mssql-password: AutoParts_Str0ng!
  redis-password: autoparts_redis
  rabbitmq-password: autoparts_pass