FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Копируем оба csproj
COPY ["src/services/Orders.API/Orders.API.csproj", "src/services/Orders.API/"]
COPY ["src/Shared.Contracts/Shared.Contracts.csproj", "src/Shared.Contracts/"]
RUN dotnet restore "src/services/Orders.API/Orders.API.csproj"

# Копируем весь код
COPY . .
RUN dotnet publish "src/services/Orders.API/Orders.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

# ← это исправляет libgssapi_krb5.so.2
RUN apt-get update && apt-get install -y libgssapi-krb5-2 && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "Orders.API.dll"]