FROM node:20-alpine AS build
WORKDIR /app

COPY angular-client/package*.json ./
RUN npm ci

COPY angular-client/ .
RUN npm run build

# Nginx для раздачи статики
FROM nginx:alpine AS runtime
COPY --from=build /app/dist/angular-client/browser /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80